const Dialogos = ["¿Qué hora es?", "Siento que llevo mucho tiempo atrapado en este apartamento.",
"Se parece a una foto que he visto en casa...", "Lo siento, Kei.", "Por culpa mía te has visto involucrado...",
"(Eso es...Desde el principio fue por culpa de Kato)", "(En aquella ocasión...Si no se hubiera entrometido)",
"(Iba volviendo de clases, y este tipo estaba ahí)", "(Su nombre es Kato...Masaru Kato)", 
"(Después de que Kato se cambiará de escuela, no le había visto en mucho tiempo. Me preguntaba si se acordaba de mí)",
"(Pero entonces... Me pidió que ayudará a ese vagabundo...)", "¡¡Kei!! ¿Eres Kei? ¿verdad?",
"(el que dijera mi nombre...me alegro...)","(Me obligo a ayudar a ese vagabundo...)",
"¡Está enfermo, me agacharé y lo subiré!", "(Así que... tuve que ayudar al vagabundo...)",
"(Después de eso...nos golpeó el tren que venía entrando en el andén...)", "(Pero...en...)",
"(Ese momento... en el que morí... Todo se volvió blanco...)", "(Fue entonces, me di cuenta de que estaba en este apartamento...)",
"(Me preguntaba si el mundo después de la muerte... es un apartamento)", "(Pensara lo que pensara, la Torre de Tokio se veía por la ventana)",
"(Esto es una habitación de un apartamento en Tokio)", "(Al principio pensé que era un apartamento normal)",
"(Pero no podíamos salir...)", "(Debido a que las puertas y ventanas no se pueden tocar)", "(Hay una fuerza misteriosa que nos impide hacerlo)",
"(Incluso si gritamos, nadie responde)", "(La otra cosa rara fue que...)",
"(En medio de la habitación había una gran esfera)","(Estaba hecha de metal, si la golpeas no pasa nada)",
"(¿Qué eres?)","......","(La situación es esta ahora...)","(Estoy en esta habitación... yo, Kato... y)",
"(¿Un Nini de aspecto sombrío?)", "(Un perro...)", "(¿Mm...?)", "Kei, sabes...","(¡Todo esto es culpa tuya...Todo por quedar como un Yankee Cool!)",
"En la escuela primaria, parecía que no le tenías miedo a nada, eras nuestro líder.","¿Así fue...?",
"(¿Por qué en una situación como esta se pone a recordar cosas de cuando éramos niños? ¡Que vergonzoso!)",
"Siempre me atrapaban los niños malos de la escuela.", "Empecé a trabajar más duro para ser como tú.",
"¿Eh?, (¡Porque me cuentas eso a mí!)","(Vamos, yo soy la razón por la que este tipo es así... ¿Esto es mi culpa?)",
"¿Qué?","Kei, ¿Qué es eso?","¿Qué es esto? ¿Una Chica?","¡Hey, hey, hey!","Oh... ¿Así es como llegamos?",
"No...No...","Tiene sangre en su brazo...","Debió haberse suicidado...","¿Hm...?","Disculpa...","Pero con esa apariencia, me cuesta apartar la mirada.",
"¿Eh?, disculpa... ¿Qué es este lugar?","¿Qué es esa música?","No parece venir de afuera...",
"Sus vidas han terminado cómo pasarán el resto de sus vidas eso depende de mí, esa es mi teoría.",
"¿Alien cebollense?", "¿Qué es esto? ¿qué trata de decirnos?","Se que esto puede sonar muy tonto...",
"Si te lo tomas en serio, da bastante miedo.","¿Cebollense? ¿Qué significa eso?","¿No será que es un programa de televisión?",
"¡Se ha abierto!","Tiene algo, ¿serán juguetes?","¡¿Eh?! Hay una persona adentro...","Es cierto...",
"Estos maletines...tienen nuestros nombres.","¿Qué hay dentro?","¿Qué es esto? ¿Un cosplay?","......",
"(Ese niño...)","(No dice nada...pero trae el traje puesto...)","(¿Sabe algo...?)","Kei, ¿Qué haremos?",
"Esas Armas, ¿deberíamos usarlas?","Aunque parecen juguetes...","Disculpa, pero ¿qué es esto?","¿El que?",
"Me refiero a que está sucediendo...","Ahora que lo dices...","¿Qué será...?","¿Qué pasará ahora?","Disculpa... ¿Cuál es tu nombre?",
"Mi nombre es Kato Masaru...","Yo me llamo Kurono, Kei Kurono.","¿Eh...Kurono...?","Puedes llamarme como quieras.",
"¿Y cuál es tu nombre?","Kishimoto...Kei...","(Kei...Igual que mi nombre)","Oye Kei, ¡no puedo moverme!","¡¿Ah?!",
"Se ha detenido...","¿Qué está pasando?","¿Qué está sucediendo?","¿Eh?","Es afuera.","¿Eh?","Es verdad, estamos afuera.",
"¿En qué lugar estamos?","Kato no está... ¿Kato?","Disculpa... ¿Dónde estamos?","No sé...","El Premio es de un millón...",
"¿Eh?","En esta zona se esconde un alienígena...","Si logran cazarlo, tendrán un millón.","¿Qué estás diciendo...?",
"La razón por la que fueron llevados a esa habitación...","Esto es un programa de televisión...","No puedo creerlo... ¿alienígenas?",
"Kato y yo, realmente morimos...","Solo hay una forma de saber si es verdad.","¿Y Kato?, ¿Dónde está Kato?",
"¿Quién sabe...?, cómo fue el primero en ser transportado, ¿no se habrá ido?","O tal vez ya se encargó él mismo del alienígena...",
"Y ese alienígena, ¿Dónde deberíamos buscarlo?","En este lugar.","Oh... ¿Un radar?","Está bastante cerca..., vayamos a buscarlo.",
"(Supongo que no me queda más opción que ir)","Es realmente viejo este departamento... ¿vivirá gente aquí?",
"No, podría estar adentro...","(Investigare)","¡Oh! Estaba aquí.","(¿El...Es...un Alíen?)","(Hugh...Apesta)",
"Enfrentarlo solo es peligroso...","¡Oigan! ¡Lo encontré!","Chicos, vengan...","¡Gua, Gua, Gua!",
"¿Qué estás haciendo?, acabalo de una vez.","¡Bien!","Esto no ha sido nada...","No era real, ¿cierto?, aunque se veía como si lo fuera...",
"¿Por qué no pruebas a tocarlo?","¡Qué asco!","No los has derrotado, hasta que todos estén muertos...",
"¿Hay más?","Mira, aún marca un punto...","Eso significa que queda uno con vida…","Debe ser por aquí.",
"Tengo miedo...","¿Te has asustado igual?, y si mejor te quedas aquí...(?)","No tengo miedo, vamos.","Este olor...",
"No hay duda de que es aquí.","Un cebollín, por favor.","¡¿Por qué siguen apareciendo?!","Bien...","El radar sigue marcando un lugar más.",
"Todavía queda uno más...denme un respiro.","Bien, vayamos a buscarlo.","Okey.","¿Eh?, ¿Kato?","¡Yo no los he matado!",
"Es el jefe.","¿Quién es ese?","Tiene el mismo olor...","¡¿No será que tú eres el padre de los aliens cebollense?!",
"No puede ser...","¿Ustedes hicieron esto?","¡Grrr!","¡Ah!","¡Kato!","¡Kato! ¡Kato esto es un juego!","Debes acabar con él.",
"¿Le disparó? ¿si le disparo que pasara?","¡Morirá!","¡Si no lo matas, no podremos volver!","¡Dispara, Kato!",
"¡Dispara, Kato!","No puedo...","Aunque sea un juego...no puedo matarlo.","Que patético...","¡¿Qué estás haciendo?!",
"¡Grrr!","(¿Qué le pasa?, es totalmente diferente a los demás aliens cebollense)","(¿Podré ganarle?)",
"¡Oye Padre de los cebollense!","¡El que acabó con tus hijos fui yo!","¡Grrr!","(Al tenerme arrinconado, siento que voy a morir)",
"(Aun así, no lo entiendo…)","(Bueno...Aunque muera nadie se pondría triste por eso...)","(Pareciera que voy a llorar…)",
"(¿Por qué será que me siento así?)","En la escuela primaria, parecía que no le tenías miedo a nada, eras nuestro líder.",
"Empecé a trabajar más duro para ser como tú.","¡Kei!","¡Kato!","¡No dejaré que mates a Kei!","Hah, hah, hah.",
"Quedó hecho pedazos...","Ni que lo digas...","¿Qué?","Seguramente lo disfrutaste mucho...","Te has sentido más fuerte...",
"Lo sé, desde la primera vez que te vi en la habitación lo supe.","Tú y yo, somos iguales.","¿Eh?","Disfrutaste hacerlo pedazos, ¿verdad?",
"Lo conseguimos a tiempo","¿A tiempo?, entonces después de todo si es un juego.","¡Aún sigues creyendo eso!",
"¡¿Qué has dicho?!","Ya lo has entendido, ¿no?","Esta es la realidad...Significa que no es un juego.",
"¡Si no es un juego, entonces qué está sucediendo...!","No te enojes, de todas maneras, volveremos a la habitación...",
"¿Volveremos?","Pronto... y podrán irse a sus casas.","¿Podremos volver?","¿No estamos muertos?","No, están vivos.",
"Espera y verás.","(¡¿En serio...podremos volver...será cierto?!)","Oh...me adelantare.","Era cierto...es la habitación.",
"De verdad...hemos vuelto.","Gantz dará las puntuaciones.","¿Has dicho Gantz?","Si...Gantz.","¿Tú le pusiste ese nombre?",
"No, de antes que yo llegara...","¿De antes?","Alguien...antes de que yo llegara.","Estas puntuaciones... ¿Están bien?",
"Oye, ¿a dónde vas?","A afuera, está abierto.","Espera un momento.","¿?","Hay muchas cosas que quisiera preguntarte.",
"Tu...Hay algo más que sabes, ¿cierto?","Si...","......","Por supuesto, si quieres saberlo.","Basta de mentiras...",
"¿Qué te pasa? ¿Qué eres?","Lo sabías todo desde el principio.","¿Yo...?, Soy un extraterrestre.","¿Extraterrestre? Debes estar mintiendo.",
"Jajaja.","Si, es mentira.","¡Maldito!","Yo soy normal...un chico normal de secundaria.","Llevo aquí un año.",
"¿Qué quieres decir? ","¿No lo entiendes?, no me hagas repetirlo.","Llevo un año siendo traído por las noches a esta habitación.",
"Llevó más tiempo que cualquiera y me ha tocado ver morir a muchos.","Pero he vuelto con vida...sigo aquí.","Los inútiles que llegan aquí, solo les queda morirse.",
"Aunque tú pareces ser diferente.","Fuiste el único que se dio cuenta de la importancia del traje.","Por eso saliste con vida.",
"¿Por qué no nos dijiste?","¡¿?!","¡Si nos hubieras explicado desde el principio todo, y no hubieras mentido!",
"¡No nos hubieras expuesto a tal peligro!","¿Por qué? ¿Por qué no nos lo dijiste antes?","¡No quiso decírnoslo!",
"Si les hubiera dicho, no habrían podido distraerlos, aunque no esperaba que salieran vivos.","......",
"¿Qué? ¿Estás enojado?","¿Qué pasa con esa mirada?","¿Tú... no sientes ningún remordimiento por lo que hiciste?",
"No me vengas con eso.","No me importa quien viva o muera.","¿Qué quieres hacer? ¿Quieres golpearme? A mi...",
"Eres igual que el padre de los cebollenses...","Eres un cebollense...","¡Cebollense!","¿Qué pasa? ¿Estás llorando?",
"Que patético, eres mayor, ¿no?","¡Kato! ¡Hazlo! ¡Golpéalo!","¡Sí!","No me queda de otra, estúpidos.",
"No están entendiendo nada.","De todos los que están aquí yo soy el más fuerte.","A pesar de que les conté todo, piensan que pueden utilizarme.",
"¿No crees que están bien equivocados?","Bien, ahora ¿qué parte debería volarte primero?","Baja tu arma.",
"Kei...","¡Bájala!","¿No vas a disparar? Te daré en la cabeza.","Entonces dispararé, y te volaré en pedazos.",
"......","Todavía hay muchas cosas que quiero preguntarte.","Supongo...","Tu...dijiste que estábamos vivos.",
"¿Y eso?","Antes de llegar aquí estoy seguro de que morimos, y cuando salimos parecía que las demás personas no podían vernos.",
"¿Cómo es posible que estemos vivos?, necesito saber la respuesta.","¿Realmente estamos vivos? ¿Todos nosotros?",
"Estás vivo.","Hablas en serio, ¡Oye!","Seguramente piensas que fuiste salvado justo antes de morir, ¿no es así?",
"¿Me equivoco?","Según lo que yo creo el original si murió...","¿Ah?","¿Ah?","¿Ah?","El que está aquí, fue enviado como un fax.",
"¿Qué? ¿Un fax?","Si, una copia.","Ha desaparecido.","Gantz solo trae copias a la habitación.",
"Me pregunto cuando el viejo de la esfera se cansará de esto.","Bueno...llega el momento de irse, adiós.",
"Me voy a casa, ustedes igual pueden volver a sus casas.","Pero será mejor que no cuente nada de lo que vieron o vivieron aquí.",
"Sus cabezas podrían explotar.","¿Se ha ido?","(Después de que fuimos llevados a aquella habitación con la esfera dentro...)",
"(Terminada la noche las puertas se abrieron.... pudimos salir y pedir un taxi...)","(Pero...Kishimoto no podía irse como estaba, por lo que le presté mi uniforme...)",
"(Pero no hemos hablado desde entonces...Todavía siento como si hubiese sido un sueño)",
"(En la mañana desperté pensando eso, pero al encender la televisión se registraron destrozos en la zona donde fuimos transportados)",
"Me pregunto...si todo lo que dijo Nishi fue verdad...yo realmente morí.","(Ha llegado alguien...)","¡Si...!",
"¿Qué? ¿Kishimoto?","Buenos Días.","Bu...Buenos...Buenos días.","¿Ha pasado algo?","No...solo pasaba a traerte tu uniforme.",
"¿Mi...uniforme?","Si...no recuerdas que me lo prestaste...","Hasta que pudiera pasar a mi habitación a cambiarme...","¿Has venido solo por eso?",
"Si...","......","......","Bueno...nos vemos.","¿Eh? Bueno...","(Ahora que lo pienso...)","(Nunca había visto a una chica desnuda...)",
"(Perdí mi oportunidad de pedirle su correo)","(¿Si salgo ahora estaré a tiempo de pedírselo?)","Ha venido alguien más...",
"¿Sí?","¿Qué?","......","¿sabes si...te permiten tener mascotas como perros o esas cosas?","¿Ah?, uno de mis vecinos tiene, pero...",
"Ya veo... en ese caso...","¿Eh?","Ah...Ah...Yo...","¿Kurono...Yo...podría quedarme?","¿Ah?","¿Lo siento...podría quedarme?",
"¡Claro que sí! ¡Si puedes quedarte!","¿Seguro?","Disculpa, ¿a qué te referías con mascota?","Como te decía... podría ser...como tu mascota...",
"¿Eh? ¿Eh? ¿Eh?","Aunque si no puedes...no importa.","¡No! ¡Para nada! ¡Puedo tener una!","Es raro...lo que digo, ¿no?",
"Si...","Digo no, para nada.","Para nada...eso creo.","(Kishimoto ahora está en el baño lavándose)","(¡Qué suerte! ¡qué suerte que tengo!)",
"(Que linda chica, y no tiene a donde ir)","(Es increíble, demasiado increíble)","(Yo que nunca había visto a una chica desnuda)",
"(¿Qué debería hacer?)","¡Cálmate! (En qué estaba pensando, soy tan patético)","Gracias por dejarme usar tu ducha.",
"¡Que rápido!","¿Dijiste algo?","Eh...no nada.","¿Oye...Tienes un futón?","Ahora que lo pienso... no tengo.",
"(Cierto no tengo futón, que suerte)","Ya veo.","¿Puedo dormir en la cama?","Cierto...no queda de otra...",
"(¡Lo he conseguido!)","Ya va siendo hora de dormir.","(Que bien huele...)","(¿Esto significa que está bien, si lo hago?)",
"(Bien, aquí voy...)","Kishi...","Disculpa...Kurono...","Dime...","¿Mañana irás al instituto?","¿Por qué?","Hay un lugar al que quisiera ir...",
"¿Eh? ¿Quieres que salgamos juntos?","¿No puedes?","No, si puedo ir.","¿A dónde iremos? ¿Al centro comercial o tal vez al cine o de compras?",
"Quisiera que fuéramos a mi casa...","¿Ah? ¿A tu casa?","Cuando volví a mi casa, me encontré con mi otra yo.",
" ¿Eh?","Por eso quisiera comprobarlo...","Ah...","Yo...no morí...nunca morí.","En mi casa había otra...",
"Ah...","Yo no puedo entenderlo... (*Voz temblorosa*)","Ah...","Es como si no existiera.","No tengo un lugar a donde regresar.",
"No tengo familia, ni hogar al que volver.","¿Yo que soy?","¿Qué es esto?","Kishimoto...","(Al final...no pude dormir casi nada)",
"(Y como le prometí a kishimoto...la acompañé a su casa)","(¿Realmente pueden haber dos kishimotos?)",
"Me voy...","¡Oh!","(Era verdad…es Kishimoto)","Viene hacia aquí","(¿Por qué hay dos?)","¡Menos mal…siento un peso menos encima!",
"¡Me siento bien!","Con esto…puedo relajarme.","¿Eh?","Cuando me puse a pensarlo, me di cuenta de que siempre hacía solo lo que mi mamá quería, siento que empezaré a vivir.",
"Todo el tiempo…quería que solo estudiará...","Sabiendo que no tengo que volver a esa casa.","Siento como si se me cayera un peso de encima.",
"(Ya veo…por esa razón quiso suicidarse)","(Aun así… ¿por qué dos?  ¿qué está sucediendo?)","Pero…esa chica…ósea la otra yo…tendrá que continuar con esa vida.",
"Pobrecita...","(Si hay dos Kishimotos… ¿porque no me paso a mi lo mismo?)","(Bueno…)","(De ahora en adelante, viviremos juntos)",
"¡Bien! ¡Me gusta!","¡Hay alguien que me gusta!","¿Eh?","¡Kato! ¡Me gusta Kato!","Dime Kurono, ¿sabes en que secundaria estudia Kato?",
"No sé.","Ya veo…pero siento que nos volveremos a encontrar.","Es como el destino, encontrarme con Kato.",
"¿Qué harás?, si quieres puedes irte.","Y pedirle a Kato que te cuide.","¿Puedo quedarme un tiempo aquí?",
"Si no quieres puedo irme.","¡Estoy bien…! ¡Está bien…! ¡Puedes quedarte!","(Desde entonces Kishimoto no ha dicho nada…)",
"(Para mí es como un sueño, vivir con una chica…o eso pensaba…)","(Ya se acerca…)","Oye, kishimoto, ¿no te gustaría que te haga un masaje?",
"¿Eh…? Si, por favor.","¿Eh?  No puedo moverme.","Yo tampoco...","¿Qué es esto?","¡No! ¡Otra vez!","¿Eh? ¿Eh? ¿Qué sucede?",
"(Otra vez esta habitación)","¡Maldición!","¡Kurono!","(Han llegado nuevas personas)","(Un chico)","(¿Qué le pasa a esa chica?)","¿Ustedes son compañeros?",
"¿Compañeros? Si algo así...","No me dirás tú también que he sido traído a esta habitación para matar alienígenas.","No miento, ¡es la verdad!",
"Kei, ¡díselo tú también!","Eh...si...","(Han aparecido un chico llamado Hojo y una extraña chica que se parece a Sadako)",
"(Ambos tuvieron un accidente de tránsito, aunque se lo expliquemos dudo que confíen en nosotros)",
"(Bueno...lo único que lograremos es que piensen que estamos mal de la cabeza)","¿Ves?, ¿es tal como te dije que sucedería, ahora confiaras en mí?",
"No, aún no confío en ti.","Otra vez...nos harán combatir.","¿Realmente la única manera de salir de aquí es combatiendo?",
"Así es.","Lo siguiente que pasará es que la esfera se abrirá, tengan cuidado.","¿Debo ponerme este raro traje?",
"Si, por favor. Es necesario si quieres salir con vida de aquí.","Tsk… metanse en sus asuntos","¿Podremos salir vivos de aquí?",
"Seguramente.","No te preocupes, estarémos bien.","¿Y que debería hacer de ahora en adelante?","Seremos enviados afuera, aunque estemos afuera no puedes irte.",
"Ya ha empezado.","¿Como?, ¿no entiendo que sucede, será un programa de televisión?","¿Dónde estoy?","Fui el primero en ser transportado.",
"(¡Es el!)","(¡Debe de ser una broma!)","(Los demás aun no llegan)","(¿Qué debería hacer?)","(Enfrentarlo solo es demasiado peligroso)",
"(¿por qué me pasa esto?)","¿Sato? ¿Sato?","Yo no me llamo Sato.","¿Sato?","Te dije que no soy Sato.","¡Grrrr!",
"Se ha enojado.","Debo huir.","(¡Me he caído al río!)","Kei, ¿Qué te ha pasado?","¿Eh, ya me puedo ir?",
"El enemigo se ha caído al río.","¡Todos, Vamos!","¿Eh?","De alguna manera, lo hemos conseguido.","¿Sin embargo, realmente cosas como esa existen?",
"¿No es un sueño?","¿Con esto, será suficiente para que termine?","Aunque, aún la teletransportación no empieza.",
"Será que después de todo aún quedan enemigos ahí fuera.","¿Aún no podemos volver a casa?","Cierto, usemos esa cosa parecida a un radar.",
"Lo suponía, aún quedan.","¿Qué? ¿De verdad aún queda?","Hablas en serio...","¿Qué harás ahora?","Si nos quedamos aquí no terminará...",
"No sabemos cuántos enemigos quedan.","¡Vayamos a buscarlos!","No, nos queda otra.","Este apartamento...",
"El radar indica principalmente aquí.","Ahora que lo pienso, los aliens Tanaka se deberán encontrar en este viejo departamento...",
"Es peligroso irrumpir de manera directa, será mejor entrar sigilosamente.","comprendo.","Que molestia.",
"No veo a ninguno, es solo una pérdida de tiempo.","No será que este no es el lugar correcto...","Aun así, quiero terminar esta misión cuanto antes.",
"¡Bien! entraré yo primero.","¿Eh?, ¿vas a entrar?","Hah, hah, hah.","¿Eso era todo?","¿Qué es eso?",
"¡Se está haciendo más fuerte!","¡Oigan, debemos huir afuera ahora!","¡Entendido!","¡Date prisa! ¡Se está derrumbando todo!",
"Se ha escapado.","(Ha volado a diferencia de los demás).","¡Es un pájaro gigante!","¿Qué es esa cosa?",
"Es gigantesco","(¡¿Podemos ganarle a un monstruo así?!)","¡Tranquilícense, debemos buscarle algún punto débil!",
"(¡¿Maldición, realmente tendrá algún punto débil?!)","No lo comprendo.","Oigan, antes de huir, ¡debemos encontrarle algún punto débil!",
"¡Guau!","Hah, hah, hah.","Se ha terminado.","Podremos volver...","¡Podremos volver! ¡Kato!","(Tsk…)",
"No ha sido tan difícil.","Lo que sigue, serán las puntuaciones.","¿Puntuaciones?","¿Qué significado tiene?, ¿Eso de las puntuaciones?",
"¿Podrías decirnos para qué sirven?","Eh… no lo se","¿Oye, no será que nos estás ocultando algo?","Si obtienes 100 puntos será libre...",
"¿Es eso verdad?","Aunque es solo una suposición.","¿Una suposición?","¿Qué es esto? ","¿Algo así como un juego?",
"Puede ser… un juego donde tienes que matar...","Como en un programa de televisión…jajaja","(Lo suponía, no se puede confiar en el)",
"Realmente no puedo entender esto.","¿Y qué será lo siguiente que nos haga hacer?","Una vez entregadas las puntuaciones se abre la puerta y puedes volver a casa.",
"Ya veo…por fin podremos irnos.","(Para ser llamados una vez más)","(¿Cuántas veces deberé ser llamado hasta poder salir de aquí?)"
]
const NuevosDialogos0 = ["No siento que sea necesario ponernos ese cosplay…","Bueno, si tú lo dices…"]
const NuevosDialogos1 = ["Siento que nos servirán...","¿Eh?",
"Posiblemente...no estoy seguro...pero, siento que deberíamos ponernos ese traje.",
"¿Lo sientes?, bueno, si tú lo dices...","Tú también deberías colocártelo...","¿Sí?",
"Pienso que sería mejor que te pusieras el traje...","Si..."];
const NuevosDialogos2 = ["Pareciera que estuviéramos haciendo cosplay...","(No debí habérmelo puesto...)",
"(Llevando este juguete pareciera más que estuviéramos haciendo cosplay...)","¡Ah!","¿Ah?",
"Escuché un grito del pasillo de al lado...","¡Oye, detente...!","¿Qué sucede?","La chica de antes, parece que está poniéndose el traje.",
"Oye, ¿Qué sucede?","Estoy bien, ¡Estoy bien!","Ya veo, entonces está bien.","Este cosplay creo que podría llegar a gustarme..."]